name: Build & Archive (Hugo)

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: hugo-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with LFS and submodules)
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo (extended)
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build site
        run: |
          hugo --minify --baseURL "https://www.bolotnaya.online/"

      - name: Sanity check: no localhost/old domains in output
        run: |
          set -euo pipefail
          cd public
          FOUND=0
          for p in "localhost" "127.0.0.1" "a-krivoshen.github.io" "bolotnaya.netlify.app"; do
            if grep -R -n "$p" .; then
              echo "Found forbidden reference: $p" >&2
              FOUND=1
            fi
          done
          if [ "$FOUND" -ne 0 ]; then
            exit 1
          fi

      - name: Pack clean source archive
        run: |
          mkdir -p artifacts
          OUT="artifacts/hugo-sources-${GITHUB_SHA}.tar.gz"
          tar -czf "$OUT" \
            --exclude='.git' \
            --exclude='artifacts' \
            --exclude='public' \
            --exclude='resources' \
            --exclude='node_modules' \
            --exclude='.cache' \
            --exclude='dist' \
            --exclude='.hugo_build.lock' \
            --exclude='**/.DS_Store' \
            --exclude='**/*.log' \
            --exclude='.env' \
            --exclude='**/*.key' \
            --exclude='**/*.pem' \
            --exclude='tina/__generated__' \
            .

      - name: Upload source artifact
        uses: actions/upload-artifact@v4
        with:
          name: hugo-sources-${{ github.sha }}
          path: artifacts/*.tar.gz
          retention-days: 14

      - name: Upload built site (public)
        uses: actions/upload-artifact@v4
        with:
          name: site-public-${{ github.sha }}
          path: public
          retention-days: 14

      - name: Deploy to gh-pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          cname: www.bolotnaya.online
          force_orphan: true
